name: big_dart
description: A small, fast, easy-to-use library for arbitrary-precision decimal arithmetic.
version: 1.0.1
homepage: https://github.com/serdimoa/big.dart
repository: https://github.com/serdimoa/big.dart

environment:
  sdk: '>=2.14.4 <3.0.0'


# dependencies:

dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.2
